"""Smart Orchestrator - LLM-powered query analysis and step execution."""

from __future__ import annotations

import json
import re
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field

from ..gemini_client import GeminiClient
from ..models import (
    ToolDefinition,
    IntegrationInput,
)

logger = logging.getLogger(__name__)


class ExecutionStep(BaseModel):
    """A single execution step in the flow."""
    id: str
    tool: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    depends_on: List[str] = Field(default_factory=list)
    description: str = ""
    status: str = "pending"  # pending, running, done, failed, skipped
    result: Optional[Any] = None
    error: Optional[str] = None
    started_at: Optional[str] = None
    completed_at: Optional[str] = None


class ExecutionPlan(BaseModel):
    """Complete execution plan generated by LLM."""
    steps: List[ExecutionStep] = Field(default_factory=list)
    workflow_type: str = "sequential"  # sequential, parallel, mixed
    summary: str = ""
    extracted_params: Dict[str, str] = Field(default_factory=dict)


class ExecutionLog(BaseModel):
    """A log entry for debugging."""
    timestamp: str
    level: str  # debug, info, warn, error
    stage: str  # planning, execution, completion
    step_id: Optional[str] = None
    message: str
    details: Optional[Dict[str, Any]] = None


class SmartExecutionResult(BaseModel):
    """Result of smart execution."""
    plan_id: str
    prompt: str
    plan: ExecutionPlan
    logs: List[ExecutionLog] = Field(default_factory=list)
    overall_status: str = "pending"  # pending, running, completed, partial, failed
    started_at: str
    completed_at: Optional[str] = None
    results: Dict[str, Any] = Field(default_factory=dict)


class SmartOrchestrator:
    """
    Smart orchestrator that uses LLM to:
    1. Analyze user query
    2. Generate execution steps dynamically
    3. Execute steps with real-time status updates
    4. Generate detailed logs
    """

    name = "smart-orchestrator"

    def __init__(self, gemini: GeminiClient):
        self.gemini = gemini
        self.logs: List[ExecutionLog] = []

    def _log(
        self,
        level: str,
        stage: str,
        message: str,
        step_id: Optional[str] = None,
        details: Optional[Dict[str, Any]] = None,
    ) -> ExecutionLog:
        """Create and store a log entry."""
        log_entry = ExecutionLog(
            timestamp=datetime.now(timezone.utc).isoformat(),
            level=level,
            stage=stage,
            step_id=step_id,
            message=message,
            details=details,
        )
        self.logs.append(log_entry)
        
        # Also log to Python logger
        log_func = getattr(logger, level, logger.info)
        log_msg = f"[{stage}] {message}"
        if step_id:
            log_msg = f"[{stage}][{step_id}] {message}"
        log_func(log_msg)
        
        return log_entry

    async def analyze_and_plan(
        self,
        prompt: str,
        available_tools: Dict[str, ToolDefinition],
        integrations: List[IntegrationInput],
    ) -> ExecutionPlan:
        """
        Use LLM to analyze the query and generate an execution plan.
        """
        self._log("info", "planning", f"Analyzing query: {prompt[:100]}...")

        # Build tools schema for LLM
        tools_schema = self._build_tools_schema(available_tools)
        
        # Get connected services
        connected_services = [
            i.id for i in integrations if i.status == "connected"
        ]
        
        self._log(
            "debug",
            "planning",
            f"Available tools: {len(available_tools)}, Connected services: {connected_services}",
            details={"tools": list(available_tools.keys()), "connected": connected_services},
        )

        if self.gemini.enabled:
            try:
                plan = await self._llm_generate_plan(prompt, tools_schema, connected_services)
                self._log(
                    "info",
                    "planning",
                    f"LLM generated plan with {len(plan.steps)} steps",
                    details={"steps": [s.tool for s in plan.steps]},
                )
                return plan
            except Exception as e:
                self._log(
                    "warn",
                    "planning",
                    f"LLM planning failed, falling back to heuristic: {str(e)}",
                    details={"error": str(e)},
                )

        # Fallback to heuristic planning
        plan = self._heuristic_plan(prompt, available_tools, connected_services)
        self._log(
            "info",
            "planning",
            f"Heuristic generated plan with {len(plan.steps)} steps",
            details={"steps": [s.tool for s in plan.steps]},
        )
        return plan

    def _build_tools_schema(self, tools: Dict[str, ToolDefinition]) -> str:
        """Build a JSON schema of available tools for the LLM."""
        schema = {}
        for tool_name, tool_def in tools.items():
            schema[tool_name] = {
                "description": tool_def.description,
                "inputs": tool_def.inputs,
            }
        return json.dumps(schema, indent=2)

    async def _llm_generate_plan(
        self,
        prompt: str,
        tools_schema: str,
        connected_services: List[str],
    ) -> ExecutionPlan:
        """Use LLM to generate an execution plan."""
        
        system_prompt = f"""You are an API orchestration engine.

Available tools:
{tools_schema}

Connected services: {', '.join(connected_services) if connected_services else 'None'}

RULES:
1. Analyze the user's request carefully
2. Break down the task into sequential steps using available tools
3. Each step MUST use exactly ONE tool from the available tools
4. Extract actual values from the user's request (issue keys, repo names, etc.)
5. For Jira issue operations: always start with jira.get_issue to fetch issue details
6. For GitHub branch operations:
   - Use branch_name format: "feature/{{issue_key}}" 
   - base_branch should be "main" unless specified
7. For GitHub PR operations:
   - head = the feature branch name
   - base = "main" unless specified
   - title should reference the issue
8. Do NOT skip steps - follow the logical order
9. Do NOT invent fields not in the tool schema
10. Return ONLY valid JSON - no explanations

OUTPUT FORMAT:
{{
  "steps": [
    {{
      "id": "1",
      "tool": "tool_name",
      "arguments": {{ "param": "value" }},
      "description": "What this step does"
    }}
  ],
  "workflow_type": "sequential",
  "summary": "Brief description of what the workflow does",
  "extracted_params": {{
    "issue_key": "ABC-123",
    "repo": "backend"
  }}
}}"""

        response = await self.gemini.generate_json(
            system_prompt,
            {"user_request": prompt},
            strict_json=True,
        )

        # Parse response into ExecutionPlan
        steps = []
        for step_data in response.get("steps", []):
            steps.append(ExecutionStep(
                id=str(step_data.get("id", len(steps) + 1)),
                tool=step_data.get("tool", ""),
                arguments=step_data.get("arguments", {}),
                description=step_data.get("description", ""),
                depends_on=step_data.get("depends_on", []),
            ))

        return ExecutionPlan(
            steps=steps,
            workflow_type=response.get("workflow_type", "sequential"),
            summary=response.get("summary", ""),
            extracted_params=response.get("extracted_params", {}),
        )

    def _heuristic_plan(
        self,
        prompt: str,
        tools: Dict[str, ToolDefinition],
        connected_services: List[str],
    ) -> ExecutionPlan:
        """Generate a plan using heuristics when LLM is unavailable."""
        
        normalized = prompt.lower()
        extracted_params: Dict[str, str] = {}
        steps: List[ExecutionStep] = []

        # Extract common parameters
        issue_match = re.search(r"\b([A-Z][A-Z0-9]+-\d+)\b", prompt)
        if issue_match:
            extracted_params["issue_key"] = issue_match.group(1)

        repo_match = re.search(r"\brepo(?:sitory)?\s+([a-zA-Z0-9._/-]+)", prompt, re.IGNORECASE)
        if repo_match:
            extracted_params["repo"] = repo_match.group(1)

        branch_name = f"feature/{extracted_params.get('issue_key', 'task')}"
        extracted_params["branch_name"] = branch_name

        # Detect workflow type based on keywords
        workflow_patterns = {
            "jira_github_pr": [
                "jira", "github", "pr", "pull request", "branch"
            ],
            "connect_all": [
                "connect", "all", "connectors", "readiness"
            ],
            "slack_notify": [
                "slack", "notify", "message", "channel"
            ],
            "sheets_log": [
                "sheet", "log", "record", "append"
            ],
        }

        detected_workflow = None
        for workflow, keywords in workflow_patterns.items():
            if sum(1 for kw in keywords if kw in normalized) >= 2:
                detected_workflow = workflow
                break

        # Generate steps based on detected workflow
        if detected_workflow == "jira_github_pr":
            # Jira → GitHub branch → GitHub PR workflow
            if "jira.get_issue" in tools or "jira_get_issue" in tools:
                tool_name = "jira.get_issue" if "jira.get_issue" in tools else "jira_get_issue"
                steps.append(ExecutionStep(
                    id="1",
                    tool=tool_name,
                    arguments={"issue_key": extracted_params.get("issue_key", "")},
                    description="Fetch Jira issue details",
                ))

            if "github.create_branch" in tools or "github_create_branch" in tools:
                tool_name = "github.create_branch" if "github.create_branch" in tools else "github_create_branch"
                steps.append(ExecutionStep(
                    id="2",
                    tool=tool_name,
                    arguments={
                        "repo": extracted_params.get("repo", ""),
                        "branch_name": branch_name,
                        "base_branch": "main",
                    },
                    description="Create feature branch from main",
                    depends_on=["1"],
                ))

            if "github.create_pull_request" in tools or "github_create_pull_request" in tools:
                tool_name = "github.create_pull_request" if "github.create_pull_request" in tools else "github_create_pull_request"
                steps.append(ExecutionStep(
                    id="3",
                    tool=tool_name,
                    arguments={
                        "repo": extracted_params.get("repo", ""),
                        "title": f"Fix {extracted_params.get('issue_key', 'issue')}",
                        "head": branch_name,
                        "base": "main",
                    },
                    description="Create pull request",
                    depends_on=["2"],
                ))

        elif detected_workflow == "connect_all":
            # Connect all connectors workflow
            step_id = 1
            for tool_name, tool_def in tools.items():
                if "connect" in tool_name.lower() or "status" in tool_name.lower():
                    steps.append(ExecutionStep(
                        id=str(step_id),
                        tool=tool_name,
                        arguments={},
                        description=f"Check {tool_name.split('.')[0] if '.' in tool_name else tool_name} connection",
                    ))
                    step_id += 1

        else:
            # Generic: match tools based on query keywords
            matched_tools = self._match_tools_to_query(normalized, tools)
            for idx, tool_name in enumerate(matched_tools, 1):
                tool_def = tools[tool_name]
                args = self._generate_arguments(tool_name, tool_def, extracted_params)
                steps.append(ExecutionStep(
                    id=str(idx),
                    tool=tool_name,
                    arguments=args,
                    description=tool_def.description or f"Execute {tool_name}",
                    depends_on=[str(idx - 1)] if idx > 1 else [],
                ))

        return ExecutionPlan(
            steps=steps,
            workflow_type="sequential",
            summary=f"Workflow for: {prompt[:50]}...",
            extracted_params=extracted_params,
        )

    def _match_tools_to_query(
        self,
        normalized_prompt: str,
        tools: Dict[str, ToolDefinition],
    ) -> List[str]:
        """Match tools to the query based on keywords."""
        keyword_mappings = {
            "jira": ["jira", "issue", "ticket", "bug", "task", "story"],
            "github": ["github", "repo", "branch", "pr", "pull request", "commit"],
            "slack": ["slack", "message", "channel", "notify"],
            "sheets": ["sheet", "spreadsheet", "row", "cell", "append"],
        }

        matched_services = set()
        for service, keywords in keyword_mappings.items():
            if any(kw in normalized_prompt for kw in keywords):
                matched_services.add(service)

        matched_tools = []
        for tool_name in tools:
            tool_lower = tool_name.lower()
            for service in matched_services:
                if service in tool_lower:
                    matched_tools.append(tool_name)
                    break

        return matched_tools

    def _generate_arguments(
        self,
        tool_name: str,
        tool_def: ToolDefinition,
        extracted_params: Dict[str, str],
    ) -> Dict[str, Any]:
        """Generate arguments for a tool based on extracted parameters."""
        arguments: Dict[str, Any] = {}
        
        for input_name in tool_def.inputs:
            lowered = input_name.lower()
            
            if "repo" in lowered:
                arguments[input_name] = extracted_params.get("repo", "")
            elif "issue" in lowered:
                arguments[input_name] = extracted_params.get("issue_key", "")
            elif "branch" in lowered and "base" in lowered:
                arguments[input_name] = "main"
            elif "branch" in lowered:
                arguments[input_name] = extracted_params.get("branch_name", "")
            elif "head" in lowered:
                arguments[input_name] = extracted_params.get("branch_name", "")
            elif "base" == lowered:
                arguments[input_name] = "main"
            elif "title" in lowered:
                issue_key = extracted_params.get("issue_key", "")
                arguments[input_name] = f"Fix {issue_key}" if issue_key else ""
            else:
                # Leave empty - don't generate placeholder values
                arguments[input_name] = ""

        return arguments

    def get_logs(self) -> List[ExecutionLog]:
        """Get all logs generated during orchestration."""
        return self.logs.copy()

    def clear_logs(self):
        """Clear all logs."""
        self.logs.clear()
